print("Hi, I am a robot, what is your name?")
name = input()
print("Hi", name, "how are you doing today?")
input()
print("That's interesting!, How old are you!")
age = input()
print("Oh wow, I remember being ",age, "! What school do you go to?")
school = input()
print("Sounds like a great school! Do you have a favorite food? ")
food = input()
print("Mmm delicious! Mine is batteries. What about games? Do you have a favorite?")
game = input()
print(game, "is a great game! It was a pleasure to meet you! Bye-bye")