questions_list = [
    "Name a cold place.",
    "Name a fast food restaurant",
    "Name an element on the periodic table",
    "Name a vegetable",
    "Name a piece of furniture",
    "Name an ice cream flavor",
    "Name something at iCode.",
    "Name a color",
    "Name a famous Youtuber",
    "Name a video game",
    "Name a fruit",
    "Name something you do when you're bored",
    "Name a name",
    "Name a college",
    "Name a singer",
    "Name a sport",
    "Name a soccer player",
    "Name a football player",
    "Name a brainrot slang word",
    "Name an animal",
    "Name a number below one hundred",
    "Name a shoe brand",
    "Name a mall store",
    "Name a FPS game",
    "Name a computer part",
    "Name something in a classroom",
    "Name a grocery store",
    "Name something you can buy at Best Buy",
    "Name a frozen food",
    "Name an extra curricular activity",
    "Name a feeling",
    "Name a discipline",
    "Name a US state"
]